# Generated by Django 3.1.1 on 2020-11-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('TopicName', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('IsStock', models.BooleanField(default=True)),
                ('isTrending', models.BooleanField(default=False)),
                ('TrendingScore', models.FloatField()),
                ('NumberOfPosts', models.IntegerField()),
            ],
        ),
    ]
