# Generated by Django 3.1.1 on 2020-11-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TopicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='CurrentMA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='PreviousMA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='TimeOfLastPost',
            field=models.IntegerField(default=0),
        ),
    ]
