# Generated by Django 3.1.1 on 2020-11-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TopicApp', '0002_auto_20201103_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='CurrentMA',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='PreviousMA',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='TimeOfLastPost',
        ),
    ]
