# Generated by Django 3.1.1 on 2020-11-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Text',
            new_name='Post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Image',
            new_name='PostImage',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Topic',
            new_name='TopicName',
        ),
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='Anonymous',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='PostDate',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='post',
            name='PostId',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='PostType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='UserId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='Username',
            field=models.CharField(default='', max_length=256),
        ),
    ]
