# Generated by Django 3.1.1 on 2020-11-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='UserId',
        ),
    ]
