# Generated by Django 3.1.1 on 2020-11-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('PostId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(default='', max_length=256)),
                ('TopicName', models.CharField(default='', max_length=256)),
                ('PostType', models.IntegerField(default=0)),
                ('Post', models.CharField(default='', max_length=256)),
                ('PostDate', models.CharField(default='', max_length=256)),
                ('Downvotes', models.IntegerField(default=0)),
                ('Upvotes', models.IntegerField(default=0)),
                ('Anonymous', models.IntegerField(default=0)),
                ('PostImage', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
