# Generated by Django 3.1.1 on 2020-11-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowsTopic',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('TopicFollowed', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=64)),
                ('FullName', models.CharField(default='', max_length=64)),
                ('Email', models.CharField(max_length=64)),
                ('Password', models.CharField(max_length=64)),
                ('UserAge', models.IntegerField(default=0)),
            ],
        ),
    ]
