# Generated by Django 3.1.1 on 2020-09-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Username', models.CharField(max_length=100)),
                ('UserEmail', models.CharField(max_length=100)),
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
