# Generated by Django 3.1.1 on 2020-10-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20200928_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='DateOfJoining',
        ),
        migrations.AddField(
            model_name='users',
            name='FullName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='UserAge',
            field=models.IntegerField(default=0),
        ),
    ]
