# Generated by Django 3.1.1 on 2020-10-06 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20201006_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='UserAge',
        ),
        migrations.AddField(
            model_name='users',
            name='Bio',
            field=models.CharField(default='empty', max_length=256),
        ),
        migrations.AddField(
            model_name='users',
            name='BirthDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='users',
            name='ProfileImage',
            field=models.CharField(default='empty', max_length=256),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='FullName',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='users',
            name='Username',
            field=models.CharField(max_length=64),
        ),
    ]
