# Generated by Django 3.1.1 on 2020-10-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_auto_20201006_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='BirthDate',
        ),
        migrations.AddField(
            model_name='users',
            name='UserAge',
            field=models.IntegerField(default=0),
        ),
    ]
