# Generated by Django 3.1.1 on 2020-10-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_auto_20201006_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
