# Generated by Django 3.1.1 on 2020-10-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
