# Generated by Django 3.1.1 on 2020-10-08 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0007_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Bio',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ProfileImage',
        ),
    ]
