# Generated by Django 3.1.1 on 2020-10-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0008_auto_20201008_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='Following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='NumberOfPosts',
            field=models.IntegerField(default=0),
        ),
    ]
