# Generated by Django 3.1.3 on 2020-11-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=64)),
                ('TopicName', models.CharField(default='', max_length=64)),
                ('UniqueIdentifier', models.CharField(default='', max_length=64)),
                ('TextField', models.CharField(default='', max_length=256)),
                ('Upvotes', models.IntegerField(default=0)),
                ('Downvotes', models.IntegerField(default=0)),
            ],
        ),
    ]
