# Generated by Django 3.1.1 on 2020-10-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=64)),
                ('Bio', models.CharField(default='empty', max_length=256)),
                ('ProfileImage', models.CharField(default='empty', max_length=256)),
            ],
        ),
    ]
