# Generated by Django 3.1.1 on 2020-11-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Username',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
